### ISSUE TITLE
Implement small DX12/Vulkan viewer using fx-gltf

### ISSUE THREAD

**Issue by jessey-git** [jessey-git/fx-gltf#13]
Goal:
* Real world use case (may find fx-gltf problems)
* Create APIs to help interpret the Buffer data (practical experience will yield better APIs)

Main Requirements:
* API abstraction layer so we can use both Vulkan and DX12
    * No immediate mode rendering
* Simple mouse movements (Rotate, Pan, Zoom etc.)
* A "solid" lighting view (no materials)
* Able to load/use material data
    * Implement shaders as necessary (perhaps use HLSL exclusively and output GLSL from that...) 
    * Pick a "good" image load library / limit to only .png files perhaps?

Other Requirements:
* A PBR implementation

Usage/display of Animation/Skinning data need not be handled as those may be very difficult to work with.

**Comment by jessey-git** [comment]
Checked in an initial viewer into examples/

It generally shows how to go from glTF using fx::gltf to a workable solution for simple scene rendering, however, most advanced items like materials and mouse-movements are not implemented yet.

Vulkan exploration has not started but generally things should be separated enough for there to be no problem integrating it in.

**Comment by jessey-git** [comment]
Checked in a PBR+IBL implementation to basically complete this task.  The only items remaining are keyboard/mouse control and animation/skinning but those can come later if need be.

**Comment by valdirSalgueiro** [comment]
Hi, is there any possibility to have an example using directx 11? directx 11 is more widespread and im having trouble converting the sample code. Btw nice work on the dx12 viewer, looks very nice :)
