### ISSUE TITLE
Compile error in void fx::gltf::detail::Save

### ISSUE THREAD

**Issue by pdJeeves** [jessey-git/fx-gltf#45]
Error message:

../fx-gltf/include/fx/gltf.h: In function ‘void fx::gltf::detail::Save(const fx::gltf::Document&, std::__cxx11::string, bool)’:
../fx-gltf/include/fx/gltf.h:956:35: error: conversion from ‘const fx::gltf::Document’ to non-scalar type ‘nlohmann::json {aka nlohmann::basic_json<>}’ requested
             nlohmann::json json = document;

In G++ on ubuntu 17.2, happens with -std=c++14 as well as -std=c++17

**Comment by jessey-git** [comment]
Can you let me know the exact versions of your gcc and of nlohmann/json you're trying to use?

The most recent automated build from the 'updates' branch seemed to pass fine.

**Comment by pdJeeves** [comment]
i downloaded both from the main branches the day i commented. 

json is marked v3.2.0

$ g++ --version
g++ (Ubuntu 7.2.0-8ubuntu3.2) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.

I'm using Qt creator as a build environment, they may have done something weird

Flags:

g++ -c -pipe -Werror=pedantic -std=c++14 `sdl2-config --cflags` -g -Wall -W -D_REENTRANT -fPIC -DAS_NO_EXCEPTIONS -DGL_2=0 -DQT_QML_DEBUG ../src/glft/meshloader.cpp

**Comment by jessey-git** [comment]
Hmm, very odd. I cannot repro here using json 3.2.0 and g++ using a somewhat similar set of g++ options for the unit tests:
```
g++-7 (Ubuntu 7.3.0-16ubuntu3) 7.3.0
```

Are you able to do the following while I explore some source code changes:
- Switch to my 'updates' branch as it contains a local copy of 3.2.0 which is used for the unit tests
- Build and run the unit tests as per the README and see if that succeeds

**Comment by pdJeeves** [comment]
Okay, took a while because it couldn't find the include directory (i'm not accustomed to cmake!) and the tests built successfully.

The included json.hpp is 581.9 KiB and the one i cloned yesterday is 633.4 KiB

Built my project against the header in the update branch and it built successfully.
