### ISSUE TITLE
what's wrong?

### ISSUE THREAD

**Issue by ErwinMeulman** [jessey-git/fx-gltf#52]
![03-02-2019 00-43-07](https://user-images.githubusercontent.com/22874090/52170567-fa30a300-274c-11e9-921b-fa6d70ba7f5e.png)

**Comment by jessey-git** [comment]
Hmm, not sure.  Are you able to provide a .gltf file that reproduces that problem?

**Comment by jessey-git** [comment]
No response after 6 months. Closing.
