### ISSUE TITLE
Accessor validation message

### ISSUE THREAD

**Issue by torokze** [jessey-git/fx-gltf#67]
Hi,

If the accessor's component type not float the gltf validation shows a lot of INTEGER_WRITTEN_AS_FLOAT message. The min/max vector element type always float.

Zolee

**Comment by jessey-git** [comment]
Hi torokze, can you provide more details on how you received the validation error?  Were you crafting the file manually using the fx-gltf api?

**Comment by torokze** [comment]
Hi,
When I'm creating meshes using "indices" the index buffer min/max property written as a float value instead integer. Yes, I'm using fx-gltf to export a model from a CAD software.

The indexIV based on uint.
The localCreateGltfAccessor just a simple function to emplace a new accessor instance into an std::vector.

`const auto gltfAccessorIdx = localCreateGltfAccessor();`
`auto& gltfAccessor = gltfAccessors[gltfAccessorIdx];`
`gltfAccessor.bufferView = 2;`
`gltfAccessor.componentType = gltf::Accessor::ComponentType::UnsignedInt;`
`gltfAccessor.byteOffset = indexStart * sizeof(indices.front());`
`gltfAccessor.type = gltf::Accessor::Type::Scalar;`
`gltfAccessor.count = polyIndices.size();`
`gltfAccessor.min.push_back(indexIV.min);`
`gltfAccessor.max.push_back(indexIV.max);`
`gltfPrimitive.indices = gltfAccessorIdx;`

These accessors produces the warnings because the min/max values postfixed with '.0'.

Zolee

**Comment by jessey-git** [comment]
Ah, now I see, yes you are correct.  I will attempt a fix when I can.  In the meantime, if your applications support it, I believe the min/max values for Indices are optional and need not be specified.

**Comment by jessey-git** [comment]
Give master a try if you can. This should now be fixed, thanks for reporting!
