### ISSUE TITLE
`application/gltf-buffer` data uris not supported

### ISSUE THREAD

**Issue by u3shit** [jessey-git/fx-gltf#68]
This issue came up while trying a few sample models from the gltf sample repository, for example here:
https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/SimpleSparseAccessor/glTF-Embedded/SimpleSparseAccessor.gltf
Trying to load that model fails with `Invalid buffer.uri value`.

There's an issue about this in the glTF-Sample-Models repo, but they say the models are fine and the specification need a PR: https://github.com/KhronosGroup/glTF-Sample-Models/issues/244
That PR hasn't received any significant update since Dec 2017, so I'm not sure what would be the best thing to do, but fx-gltf should at least accept the `application/gltf-buffer` mimetype along with `application/octet-stream`, since there are models out there using that.

Version: fx-gltf 1.1.0

**Comment by jessey-git** [comment]
I've decided to go ahead and allow this.  It's been checked in now and will soon be part of the 1.2.0 release here.
