### ISSUE TITLE
Does not build with the nlohmann/json versions 3.8 and newer

### ISSUE THREAD

**Issue by enci** [jessey-git/fx-gltf#72]
Thank you a fantastic library that I use daily!

I've tried to update to latest today. Does not build with the nlohmann/json versions 3.8 and newer due to `static basic_json parse(detail::span_input_adapter&& i, const parser_callback_t cb = nullptr, const bool allow_exceptions = true)` being deprecated. It's used in line 1862.

**Comment by jessey-git** [comment]
Give master a try if you can. This should now be fixed, thanks for reporting!
