### ISSUE TITLE
Error with "fx::gltf::Accessor::Sparse"

### ISSUE THREAD

**Issue by kaiyeh0913** [jessey-git/fx-gltf#75]
Thank you for this wonderful gltf parsing library.

I was trying to build up a gltf file from triangle mesh structure and it turned out really well. But when I was compiling the file, it would pop up this error.
![error](https://user-images.githubusercontent.com/13307940/98976792-65d8a000-24dd-11eb-8350-e1f4e1215679.JPG)

Although it will still complete the compile and the generated gltf seems to be okay, I'm still wondering is there anything I could do to avoid this error? Thanks a lot.

**Comment by jessey-git** [comment]
Thanks for brining that to my attention. I've made a fix as part of #79 which will hopefully be part of a release soon.
