### ISSUE TITLE
Out of bounds access reading GLBs

### ISSUE THREAD

**Issue by technik** [jessey-git/fx-gltf#77]
Line 1912 of LoadFromBinary reads like this:
`nlohmann::json::parse(&json[0], &json[header.jsonHeader.chunkLength]),`
But json is a vector of exactly size header.jsonHeader.chunkLength, which makes the second access an out of bounds access. This is intended behavior because the code is trying to get a pointer just _after_ the end of the vector, but it is technically illegal (and undefined behavior!), and visual studio throws an exception in when compiling in debug.
The fix is really simple though, we can just change that line to be:
`nlohmann::json::parse(json.begin(), json.end()),`

**Comment by jessey-git** [comment]
Indeed. Thank you for brining that to my attention. I've made a fix and will try to get a release going this weekend.
