### ISSUE TITLE
Missing ComponentType Int (5124) 

### ISSUE THREAD

**Issue by timskillman** [jessey-git/fx-gltf#81]
Hi,

I'm attempting to implement your excellent gltf.h header into my code and found that
~~~
Int = 5124
~~~
... is missing in the ComponentType enum class.  

Is that correct?

Thanks

**Comment by jessey-git** [comment]
Oddly enough, that type is not defined in the specification: https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#accessor-element-size

**Comment by timskillman** [comment]
That's strange? Having worked with TinyGLTF they've spec'd that value so I
assumed it was in the original too
Thanks

**Comment by jessey-git** [comment]
Closing this one out now.
