### ISSUE TITLE
DefaultMaxMemoryAllocation should be dynamic

### ISSUE THREAD

**Issue by timskillman** [jessey-git/fx-gltf#82]
The 'DefaultMaxMemoryAllocation' in gltf.h is set too small for a number of larger glTF models.

Ideally this should increase dynamically.

**Comment by jessey-git** [comment]
The memory quota is adjustable by the user when reading the file. If the user is ok with potentially allocating large amounts of memory (a hostile gltf can specify a size much larger than what's present) they can increase it.

Pass in a `fx::gltf::ReadQuotas` struct to the `fx::gltf::LoadFromBinary` method

**Comment by timskillman** [comment]
Thanks - understood.  I'll do that.

I've got your code working in an Editor I'm working on for the Raspberry Pi
- your code is smaller, faster and more compact than TinyGLTF which is why
I'm using it.
Currently working on implementing animations ...

[image: Pi3Cmodeller.png]

Thanks again for your great work!

All the best

Tim

**Comment by jessey-git** [comment]
Cool!  Glad it's helped you get started on your project.

**Comment by timskillman** [comment]
Thank you!

**Comment by jessey-git** [comment]
Closing.
